plugins {
    id("studioone.android.application")
    id("studioone.android.hilt")
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.google.services)
    alias(libs.plugins.firebase.crashlytics)
    alias(libs.plugins.baselineprofile)
}

android {
    // BuildConfig carries backend endpoints — injected from CI secrets so no
    // keys ever live in git (see .github/workflows/release.yml).
    buildFeatures {
        buildConfig = true
        compose = true
    }

    defaultConfig {
        buildConfigField("String", "SUPABASE_URL", "\"${providers.gradleProperty("S1_SUPABASE_URL").getOrElse("https://studioone.supabase.co")}\"")
        buildConfigField("String", "SUPABASE_ANON_KEY", "\"${providers.gradleProperty("S1_SUPABASE_ANON_KEY").getOrElse("public-anon-key-placeholder")}\"")
        buildConfigField("String", "REALTIME_URL", "\"${providers.gradleProperty("S1_REALTIME_URL").getOrElse("wss://studioone.supabase.co/realtime/v1")}\"")
    }

    // ABI splits configured by the application convention plugin.
    androidResources {
        generateLocaleConfig = true // per-app language support (API 33+, AppCompat fallback below)
    }
}

dependencies {
    implementation(projects.core.model)
    implementation(projects.core.common)
    implementation(projects.core.designsystem)
    implementation(projects.core.ui)
    implementation(projects.core.domain)
    implementation(projects.core.data)
    implementation(projects.core.database)
    implementation(projects.core.datastore)
    implementation(projects.core.network)
    implementation(projects.core.realtime)
    implementation(projects.core.audio)
    implementation(projects.core.midi)
    implementation(projects.core.analytics)

    implementation(projects.feature.auth)
    implementation(projects.feature.onboarding)
    implementation(projects.feature.projects)
    implementation(projects.feature.arranger)
    implementation(projects.feature.mixer)
    implementation(projects.feature.pianoroll)
    implementation(projects.feature.instruments)
    implementation(projects.feature.effects)
    implementation(projects.feature.loops)
    implementation(projects.feature.collab)
    implementation(projects.feature.social)
    implementation(projects.feature.export)
    implementation(projects.feature.settings)
    implementation(projects.feature.paywall)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.material3.window)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.hilt.navigation.compose)
    implementation(libs.androidx.media3.session)
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.hilt.ext.work)
    implementation(libs.play.services.auth)
    implementation(libs.facebook.login)
    implementation(libs.appauth)
    implementation(libs.androidx.profileinstaller)

    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.crashlytics)
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.messaging)

    debugImplementation(libs.leakcanary)

    testImplementation(libs.junit)
    testImplementation(libs.truth)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.espresso.core)
    androidTestImplementation(libs.compose.ui.test.junit4)
    debugImplementation(libs.compose.ui.test.manifest)
}

baselineProfile {
    // Generated by the :baselineprofile module against the benchmark build.
    mergeIntoMain = true
    saveInSrc = true
}
